name: Publish Documentation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  deploy:
    if: ${{ github.repository == 'bmad-sim/pytao' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip3 install -r docs-requirements.txt
      - name: Build Docs
        run: |
          pushd docs
          make html
          popd
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html/
