name: Publish Documentation

on:
  push:
  pull_request:
    branches:
      - '**'

jobs:
  deploy:
    if: ${{ github.repository == 'bmad-sim/pytao' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install pandoc -y
          sudo apt install python3-testresources
          pip3 install -U setuptools wheel
          pip3 install -U -r docs-requirements.txt
          pip3 install -U -r requirements.txt
      - name: Build Docs
        run: |
          pushd docs
          python3 -m sphinx -b html source build
          popd
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/
